### ISSUE TITLE
Feasibility and Capability of Inference on CPU

### ISSUE THREAD

**Issue by leonbaiyu** [neufieldrobotics/NeuFlow_v2#10]
Hi there,

I have a usecase for your model on a spacecraft but the onboard system will only have a 1 GHz CPU and no dedicated GPU. I wanted to ask whether you believe it would be possible to implement your model on this level of hardware. 

I have attempted to and failed to carry out inference on the CPU also.

**Comment by fherran** [comment]
I think you need to make changes to the model architecture code.

Usually by replacing device variable with "cpu" instead of "0" or "cuda".

**Comment by leonbaiyu** [comment]
I have tried this. There are challenges with regards to the half precision floating point data types. What exactly the problem is is not clear to me.

**Comment by fherran** [comment]
Have you attempted to adjust the quantization settings of the model to prevent it from defaulting to half-precision (FP16)?

I'll try to do the inference via a CPU and will let you know

**Comment by Study-is-happy** [comment]
Hi leonbaiyu, you can change the datatype to FP32 instead of default FP16, by searching "amp" and make it False. Thank you

**Comment by leonbaiyu** [comment]
> Hi leonbaiyu, you can change the datatype to FP32 instead of default FP16, by searching "amp" and make it False. Thank you

Thank you for this. This solved the problem and now I'm able to infer fairly quickly on CPU. 

Specifically, I removed any .cuda(), replaced 'cuda' device calls to 'cpu', replaced any .half() with float, and specified in model.init_bhwd for amp = False.

No changes were required within the actual NeuFlow code, changes were only required in infer.py .

The results are looking promising. We'll be in touch if we end up using your model in our applications.
