### ISSUE TITLE
updated neuflow_mixed.pth

### ISSUE THREAD

**Issue by huangyongbobo** [neufieldrobotics/NeuFlow_v2#4]
Great work! What optimizations have you made to the newly updated neuflow_mixed.pth?

**Comment by Study-is-happy** [comment]
We didn't update the model architecture. We just train more iterations on mixed datasets.

**Comment by mertkaraoglu** [comment]
Hi @Study-is-happy , thanks for open-sourcing it! What is specifically used for the mixed dataset? I believe this is the model that is refered as  "For real-world use cases, we also train the model with a mixed dataset that includes FlyingThings, Sintel, KITTI, HD1K, and VIPER [37]. The pretrained model is available in our repository."  in the paper, is that right? How many iterations is used during this step?
